<Project>
  <PropertyGroup>
    <Authors>SPNet contributors</Authors>
    <Company>SPNet contributors</Company>
    <Product>SPNet Workflow</Product>
    <Copyright>Copyright (c) SPNet contributors</Copyright>
    <PackageProjectUrl>https://github.com/spnet-workflow/spnet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/spnet-workflow/spnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>SharePoint;Workflow;WorkflowManager;CSharp;XAML;SPNet</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(ContinuousIntegrationBuild)' == '' and '$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" Link="README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" PrivateAssets="all" />
  </ItemGroup>
</Project>
