schemaVersion: spnet.workflow/v1
name: YamlHttpWorkflow
target:
  type: Site
variables:
  - name: currentListId
    type: Guid
  - name: restListEntityTypeName
    type: String
  - name: httpStatusCode
    type: String
  - name: currentUserTitle
    type: String
stages:
  - name: HTTP call
    actions:
      - type: assign
        to: currentListId
        value:
          type: getCurrentListId
      - type: lookupRestPropertyName
        listId:
          variable: currentListId
        propertyName:
          literal: ListItemEntityTypeFullName
        to: restListEntityTypeName
      - type: callHttpWebService
        address:
          type: formatString
          literal: "{0}/_api/web/currentuser"
          value:
            type: lookupWorkflowContext
            propertyName: CurrentWebUrl
        requestType:
          literal: GET
        responseStatusCodeTo: httpStatusCode
        responseContentTo: httpResponseContent
        responseHeadersTo: httpResponseHeaders
      - type: getDynamicValueProperty
        source: httpResponseContent
        propertyName:
          literal: Title
        to: currentUserTitle
      - type: writeHistory
        message:
          type: formatString
          literal: "HTTP status/user: {0}"
          value:
            variable: currentUserTitle
